### ISSUE TITLE
自动更新谷歌浏览器版本

### ISSUE THREAD

**Issue by mojimojijiujiu** [LUORANCHENG/CuttleFish_ChatGpt2.0#2]
Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 114.0.5735.134 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x00466463+2188387]
	Ordinal0 [0x003FE461+1762401]
	Ordinal0 [0x00313D78+802168]
	Ordinal0 [0x00334E59+937561]
	Ordinal0 [0x00330A6C+920172]
	Ordinal0 [0x0032E331+910129]
	Ordinal0 [0x00361430+1119280]
	Ordinal0 [0x0036108A+1118346]
	Ordinal0 [0x0035C5F6+1099254]
	Ordinal0 [0x00336BE0+945120]
	Ordinal0 [0x00337AD6+948950]
	GetHandleVerifier [0x007071F2+2712546]
	GetHandleVerifier [0x006F886D+2652765]
	GetHandleVerifier [0x004F002A+520730]
	GetHandleVerifier [0x004EEE06+516086]
	Ordinal0 [0x0040468B+1787531]
	Ordinal0 [0x00408E88+1805960]
	Ordinal0 [0x00408F75+1806197]
	Ordinal0 [0x00411DF1+1842673]
	BaseThreadInitThunk [0x75C800C9+25]
	RtlGetAppContainerNamedObjectPath [0x775A7B4E+286]
	RtlGetAppContainerNamedObjectPath [0x775A7B1E+238]
  File "D:\CuttleFish_ChatGpt2.0-main\tools\write_cookies.py", line 21, in login_baidu
    driver = webdriver.Chrome()
  File "D:\CuttleFish_ChatGpt2.0-main\tools\write_cookies.py", line 53, in main
    login_baidu(name,password)
  File "D:\CuttleFish_ChatGpt2.0-main\tools\get_cookies.py", line 20, in get_cookies
    write_cookie(str(ac),acs[ac])
  File "D:\CuttleFish_ChatGpt2.0-main\tools\get_cookies.py", line 25, in main
    return get_cookies()
  File "D:\CuttleFish_ChatGpt2.0-main\main.py", line 59, in <module>
    cookies = get_cookies()
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 103
Current browser version is 114.0.5735.134 with binary path C:\Program Files\Google\Chrome\Application\chrome.exe
Stacktrace:
Backtrace:
	Ordinal0 [0x00466463+2188387]
	Ordinal0 [0x003FE461+1762401]
	Ordinal0 [0x00313D78+802168]
	Ordinal0 [0x00334E59+937561]
	Ordinal0 [0x00330A6C+920172]
	Ordinal0 [0x0032E331+910129]
	Ordinal0 [0x00361430+1119280]
	Ordinal0 [0x0036108A+1118346]
	Ordinal0 [0x0035C5F6+1099254]
	Ordinal0 [0x00336BE0+945120]
	Ordinal0 [0x00337AD6+948950]
	GetHandleVerifier [0x007071F2+2712546]
	GetHandleVerifier [0x006F886D+2652765]
	GetHandleVerifier [0x004F002A+520730]
	GetHandleVerifier [0x004EEE06+516086]
	Ordinal0 [0x0040468B+1787531]
	Ordinal0 [0x00408E88+1805960]
	Ordinal0 [0x00408F75+1806197]
	Ordinal0 [0x00411DF1+1842673]
	BaseThreadInitThunk [0x75C800C9+25]
	RtlGetAppContainerNamedObjectPath [0x775A7B4E+286]
	RtlGetAppContainerNamedObjectPath [0x775A7B1E+238]

**Comment by LUORANCHENG** [comment]
Message: session not created: This version of ChromeDriver only supports Chrome version 103：驱动版本和浏览器版本不对应
解决方法：根据浏览器版本下载对应的驱动
